[package]
org = "sharecare"
name = "enhanced_rewrite_resource_path"
version = "1.0.1"
export = ["enhanced_rewrite_resource_path"]
distribution = "2201.5.1"
keywords=["choreo-apim-mediation-policy", "choreo-apim-mediation-request-flow"]
visibility = "private"

[build-options]
observabilityIncluded = true
